dive.c: fix compile error for missing INT_MAX
file requires <limits.h> to solve:
error: INT_MAX undeclared

gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)

Signed-off-by: Lubomir I. Ivanov <neolit123@gmail.com>
Signed-off-by: Dirk Hohndel <dirk@hohndel.org>